server:
  port: 8888

logging:
  level:
    root: info

spring:
  application:
    name: spring-ai-demo
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    deepseek:
      model: deepseek-reasoner
      base-url: https://api.deepseek.com/v1
      temperature: 0.2
      max-tokens: 1024
